import { Knex } from 'knex';

export interface DefaultLaptopSeed {
  brand: string;
  model_name: string;
  cpu_name: string;
  cpu_score: number;
  gpu_name: string;
  gpu_score: number;
  ram_gb: number;
  storage_type: string;
  storage_gb: number;
  display_size: number;
  refresh_rate: number;
  battery_wh: number;
  weight_kg: number;
  price: number;
  currency: string;
  os: string;
  category: string;
  confidence_score: number;
  wilson_lower_bound: number;
  positive_ratio: number;
  review_count: number;
  clean_review_count: number;
}

export const DEFAULT_LAPTOPS: DefaultLaptopSeed[] = [
  {
    brand: 'Apple',
    model_name: 'MacBook Air M2 13.6"',
    cpu_name: 'Apple M2 (8-Core)',
    cpu_score: 80,
    gpu_name: 'Apple M2 10-Core GPU',
    gpu_score: 65,
    ram_gb: 8,
    storage_type: 'SSD',
    storage_gb: 256,
    display_size: 13.6,
    refresh_rate: 60,
    battery_wh: 52.6,
    weight_kg: 1.24,
    price: 89990,
    currency: 'INR',
    os: 'macOS',
    category: 'Productivity',
    confidence_score: 93.4,
    wilson_lower_bound: 0.912,
    positive_ratio: 96.2,
    review_count: 52,
    clean_review_count: 48
  },
  {
    brand: 'Apple',
    model_name: 'MacBook Air M3 13.6"',
    cpu_name: 'Apple M3 (8-Core)',
    cpu_score: 86,
    gpu_name: 'Apple M3 10-Core GPU',
    gpu_score: 72,
    ram_gb: 16,
    storage_type: 'SSD',
    storage_gb: 512,
    display_size: 13.6,
    refresh_rate: 60,
    battery_wh: 52.6,
    weight_kg: 1.24,
    price: 104990,
    currency: 'INR',
    os: 'macOS',
    category: 'Productivity',
    confidence_score: 95.8,
    wilson_lower_bound: 0.938,
    positive_ratio: 97.8,
    review_count: 64,
    clean_review_count: 60
  },
  {
    brand: 'Apple',
    model_name: 'MacBook Pro 14" M3 Pro',
    cpu_name: 'Apple M3 Pro (11-Core)',
    cpu_score: 92,
    gpu_name: 'Apple M3 Pro 14-Core GPU',
    gpu_score: 88,
    ram_gb: 18,
    storage_type: 'SSD',
    storage_gb: 512,
    display_size: 14.2,
    refresh_rate: 120,
    battery_wh: 70.0,
    weight_kg: 1.61,
    price: 189990,
    currency: 'INR',
    os: 'macOS',
    category: 'Creative',
    confidence_score: 96.5,
    wilson_lower_bound: 0.945,
    positive_ratio: 98.2,
    review_count: 58,
    clean_review_count: 55
  },
  {
    brand: 'Apple',
    model_name: 'MacBook Pro 16" M3 Max',
    cpu_name: 'Apple M3 Max (14-Core)',
    cpu_score: 98,
    gpu_name: 'Apple M3 Max 30-Core GPU',
    gpu_score: 95,
    ram_gb: 36,
    storage_type: 'SSD',
    storage_gb: 1024,
    display_size: 16.2,
    refresh_rate: 120,
    battery_wh: 100.0,
    weight_kg: 2.16,
    price: 329990,
    currency: 'INR',
    os: 'macOS',
    category: 'Creative',
    confidence_score: 97.2,
    wilson_lower_bound: 0.952,
    positive_ratio: 99.0,
    review_count: 42,
    clean_review_count: 40
  },
  {
    brand: 'Dell',
    model_name: 'XPS 13 9340',
    cpu_name: 'Intel Core Ultra 7 155H',
    cpu_score: 84,
    gpu_name: 'Intel Arc Graphics',
    gpu_score: 55,
    ram_gb: 16,
    storage_type: 'SSD',
    storage_gb: 512,
    display_size: 13.4,
    refresh_rate: 120,
    battery_wh: 55.0,
    weight_kg: 1.19,
    price: 134990,
    currency: 'INR',
    os: 'Windows 11',
    category: 'Ultrabook',
    confidence_score: 87.6,
    wilson_lower_bound: 0.854,
    positive_ratio: 90.5,
    review_count: 48,
    clean_review_count: 42
  },
  {
    brand: 'Dell',
    model_name: 'XPS 15 9530',
    cpu_name: 'Intel Core i7-13700H',
    cpu_score: 86,
    gpu_name: 'NVIDIA GeForce RTX 4060',
    gpu_score: 78,
    ram_gb: 32,
    storage_type: 'SSD',
    storage_gb: 1024,
    display_size: 15.6,
    refresh_rate: 60,
    battery_wh: 86.0,
    weight_kg: 1.92,
    price: 179990,
    currency: 'INR',
    os: 'Windows 11',
    category: 'Creative',
    confidence_score: 89.2,
    wilson_lower_bound: 0.871,
    positive_ratio: 92.0,
    review_count: 45,
    clean_review_count: 40
  },
  {
    brand: 'Dell',
    model_name: 'Inspiron 15 3520',
    cpu_name: 'Intel Core i5-1235U',
    cpu_score: 62,
    gpu_name: 'Intel Iris Xe Graphics',
    gpu_score: 35,
    ram_gb: 8,
    storage_type: 'SSD',
    storage_gb: 512,
    display_size: 15.6,
    refresh_rate: 120,
    battery_wh: 41.0,
    weight_kg: 1.65,
    price: 42990,
    currency: 'INR',
    os: 'Windows 11',
    category: 'Budget',
    confidence_score: 76.4,
    wilson_lower_bound: 0.742,
    positive_ratio: 81.0,
    review_count: 65,
    clean_review_count: 54
  },
  {
    brand: 'Dell',
    model_name: 'Alienware m16 R2',
    cpu_name: 'Intel Core Ultra 7 155H',
    cpu_score: 85,
    gpu_name: 'NVIDIA GeForce RTX 4070 (8GB)',
    gpu_score: 88,
    ram_gb: 16,
    storage_type: 'SSD',
    storage_gb: 1024,
    display_size: 16.0,
    refresh_rate: 240,
    battery_wh: 90.0,
    weight_kg: 2.61,
    price: 169990,
    currency: 'INR',
    os: 'Windows 11',
    category: 'Gaming',
    confidence_score: 88.5,
    wilson_lower_bound: 0.862,
    positive_ratio: 91.5,
    review_count: 50,
    clean_review_count: 44
  },
  {
    brand: 'Dell',
    model_name: 'Latitude 5440',
    cpu_name: 'Intel Core i5-1335U',
    cpu_score: 68,
    gpu_name: 'Intel Iris Xe Graphics',
    gpu_score: 38,
    ram_gb: 16,
    storage_type: 'SSD',
    storage_gb: 512,
    display_size: 14.0,
    refresh_rate: 60,
    battery_wh: 54.0,
    weight_kg: 1.36,
    price: 89990,
    currency: 'INR',
    os: 'Windows 11',
    category: 'Business',
    confidence_score: 85.0,
    wilson_lower_bound: 0.828,
    positive_ratio: 88.0,
    review_count: 38,
    clean_review_count: 34
  },
  {
    brand: 'Lenovo',
    model_name: 'ThinkPad X1 Carbon Gen 11',
    cpu_name: 'Intel Core i7-1365U',
    cpu_score: 82,
    gpu_name: 'Intel Iris Xe Graphics',
    gpu_score: 40,
    ram_gb: 16,
    storage_type: 'SSD',
    storage_gb: 512,
    display_size: 14.0,
    refresh_rate: 60,
    battery_wh: 57.0,
    weight_kg: 1.12,
    price: 149990,
    currency: 'INR',
    os: 'Windows 11',
    category: 'Business',
    confidence_score: 94.2,
    wilson_lower_bound: 0.921,
    positive_ratio: 96.5,
    review_count: 55,
    clean_review_count: 50
  },
  {
    brand: 'Lenovo',
    model_name: 'Legion Pro 7i Gen 8',
    cpu_name: 'Intel Core i9-13900HX',
    cpu_score: 96,
    gpu_name: 'NVIDIA GeForce RTX 4080 (12GB)',
    gpu_score: 94,
    ram_gb: 32,
    storage_type: 'SSD',
    storage_gb: 1024,
    display_size: 16.0,
    refresh_rate: 240,
    battery_wh: 99.9,
    weight_kg: 2.80,
    price: 239990,
    currency: 'INR',
    os: 'Windows 11',
    category: 'Gaming',
    confidence_score: 95.1,
    wilson_lower_bound: 0.932,
    positive_ratio: 97.0,
    review_count: 62,
    clean_review_count: 56
  },
  {
    brand: 'Lenovo',
    model_name: 'IdeaPad Slim 5 16"',
    cpu_name: 'AMD Ryzen 5 7530U',
    cpu_score: 66,
    gpu_name: 'AMD Radeon Graphics',
    gpu_score: 36,
    ram_gb: 16,
    storage_type: 'SSD',
    storage_gb: 512,
    display_size: 16.0,
    refresh_rate: 60,
    battery_wh: 56.6,
    weight_kg: 1.89,
    price: 59990,
    currency: 'INR',
    os: 'Windows 11',
    category: 'Everyday',
    confidence_score: 84.8,
    wilson_lower_bound: 0.825,
    positive_ratio: 87.5,
    review_count: 44,
    clean_review_count: 39
  },
  {
    brand: 'Lenovo',
    model_name: 'Yoga 9i 2-in-1 14" OLED',
    cpu_name: 'Intel Core Ultra 7 155H',
    cpu_score: 84,
    gpu_name: 'Intel Arc Graphics',
    gpu_score: 55,
    ram_gb: 16,
    storage_type: 'SSD',
    storage_gb: 1024,
    display_size: 14.0,
    refresh_rate: 120,
    battery_wh: 75.0,
    weight_kg: 1.35,
    price: 139990,
    currency: 'INR',
    os: 'Windows 11',
    category: 'Creative',
    confidence_score: 91.8,
    wilson_lower_bound: 0.897,
    positive_ratio: 94.0,
    review_count: 51,
    clean_review_count: 46
  },
  {
    brand: 'Lenovo',
    model_name: 'LOQ 15IRH8 Gaming',
    cpu_name: 'Intel Core i5-13420H',
    cpu_score: 72,
    gpu_name: 'NVIDIA GeForce RTX 4050 (6GB)',
    gpu_score: 68,
    ram_gb: 16,
    storage_type: 'SSD',
    storage_gb: 512,
    display_size: 15.6,
    refresh_rate: 144,
    battery_wh: 60.0,
    weight_kg: 2.40,
    price: 74990,
    currency: 'INR',
    os: 'Windows 11',
    category: 'Gaming',
    confidence_score: 83.4,
    wilson_lower_bound: 0.812,
    positive_ratio: 86.0,
    review_count: 58,
    clean_review_count: 50
  },
  {
    brand: 'HP',
    model_name: 'Spectre x360 14 (2024)',
    cpu_name: 'Intel Core Ultra 7 155H',
    cpu_score: 85,
    gpu_name: 'Intel Arc Graphics',
    gpu_score: 55,
    ram_gb: 16,
    storage_type: 'SSD',
    storage_gb: 1024,
    display_size: 14.0,
    refresh_rate: 120,
    battery_wh: 68.0,
    weight_kg: 1.44,
    price: 154990,
    currency: 'INR',
    os: 'Windows 11',
    category: 'Creative',
    confidence_score: 93.6,
    wilson_lower_bound: 0.915,
    positive_ratio: 95.8,
    review_count: 47,
    clean_review_count: 42
  },
  {
    brand: 'HP',
    model_name: 'Envy x360 15 2-in-1',
    cpu_name: 'AMD Ryzen 7 7730U',
    cpu_score: 75,
    gpu_name: 'AMD Radeon Graphics',
    gpu_score: 42,
    ram_gb: 16,
    storage_type: 'SSD',
    storage_gb: 512,
    display_size: 15.6,
    refresh_rate: 60,
    battery_wh: 55.0,
    weight_kg: 1.78,
    price: 79990,
    currency: 'INR',
    os: 'Windows 11',
    category: 'Everyday',
    confidence_score: 83.9,
    wilson_lower_bound: 0.817,
    positive_ratio: 86.5,
    review_count: 43,
    clean_review_count: 38
  },
  {
    brand: 'HP',
    model_name: 'OMEN 16 (2023)',
    cpu_name: 'AMD Ryzen 7 7840HS',
    cpu_score: 86,
    gpu_name: 'NVIDIA GeForce RTX 4060 (8GB)',
    gpu_score: 78,
    ram_gb: 16,
    storage_type: 'SSD',
    storage_gb: 1024,
    display_size: 16.1,
    refresh_rate: 165,
    battery_wh: 83.0,
    weight_kg: 2.37,
    price: 134990,
    currency: 'INR',
    os: 'Windows 11',
    category: 'Gaming',
    confidence_score: 87.0,
    wilson_lower_bound: 0.849,
    positive_ratio: 90.0,
    review_count: 53,
    clean_review_count: 47
  },
  {
    brand: 'HP',
    model_name: 'Pavilion Plus 14 OLED',
    cpu_name: 'AMD Ryzen 7 7840U',
    cpu_score: 82,
    gpu_name: 'AMD Radeon 780M',
    gpu_score: 52,
    ram_gb: 16,
    storage_type: 'SSD',
    storage_gb: 512,
    display_size: 14.0,
    refresh_rate: 120,
    battery_wh: 68.0,
    weight_kg: 1.38,
    price: 69990,
    currency: 'INR',
    os: 'Windows 11',
    category: 'Student',
    confidence_score: 88.0,
    wilson_lower_bound: 0.858,
    positive_ratio: 91.0,
    review_count: 46,
    clean_review_count: 41
  },
  {
    brand: 'HP',
    model_name: 'Dragonfly Pro',
    cpu_name: 'AMD Ryzen 7 7736U',
    cpu_score: 80,
    gpu_name: 'AMD Radeon 680M',
    gpu_score: 48,
    ram_gb: 16,
    storage_type: 'SSD',
    storage_gb: 512,
    display_size: 14.0,
    refresh_rate: 60,
    battery_wh: 64.6,
    weight_kg: 1.29,
    price: 124990,
    currency: 'INR',
    os: 'Windows 11',
    category: 'Business',
    confidence_score: 90.5,
    wilson_lower_bound: 0.884,
    positive_ratio: 93.0,
    review_count: 40,
    clean_review_count: 36
  },
  {
    brand: 'ASUS',
    model_name: 'ROG Zephyrus G14 (2024)',
    cpu_name: 'AMD Ryzen 9 8945HS',
    cpu_score: 94,
    gpu_name: 'NVIDIA GeForce RTX 4060 (8GB)',
    gpu_score: 82,
    ram_gb: 16,
    storage_type: 'SSD',
    storage_gb: 1024,
    display_size: 14.0,
    refresh_rate: 120,
    battery_wh: 73.0,
    weight_kg: 1.50,
    price: 149990,
    currency: 'INR',
    os: 'Windows 11',
    category: 'Gaming',
    confidence_score: 94.8,
    wilson_lower_bound: 0.928,
    positive_ratio: 97.0,
    review_count: 66,
    clean_review_count: 61
  },
  {
    brand: 'ASUS',
    model_name: 'Zenbook 14 OLED UX3405',
    cpu_name: 'Intel Core Ultra 7 155H',
    cpu_score: 84,
    gpu_name: 'Intel Arc Graphics',
    gpu_score: 55,
    ram_gb: 16,
    storage_type: 'SSD',
    storage_gb: 1024,
    display_size: 14.0,
    refresh_rate: 120,
    battery_wh: 75.0,
    weight_kg: 1.20,
    price: 94990,
    currency: 'INR',
    os: 'Windows 11',
    category: 'Ultrabook',
    confidence_score: 93.2,
    wilson_lower_bound: 0.910,
    positive_ratio: 95.5,
    review_count: 57,
    clean_review_count: 52
  },
  {
    brand: 'ASUS',
    model_name: 'TUF Gaming A15',
    cpu_name: 'AMD Ryzen 7 7735HS',
    cpu_score: 78,
    gpu_name: 'NVIDIA GeForce RTX 4050 (6GB)',
    gpu_score: 68,
    ram_gb: 16,
    storage_type: 'SSD',
    storage_gb: 512,
    display_size: 15.6,
    refresh_rate: 144,
    battery_wh: 90.0,
    weight_kg: 2.20,
    price: 79990,
    currency: 'INR',
    os: 'Windows 11',
    category: 'Gaming',
    confidence_score: 85.5,
    wilson_lower_bound: 0.833,
    positive_ratio: 88.5,
    review_count: 60,
    clean_review_count: 53
  },
  {
    brand: 'ASUS',
    model_name: 'Vivobook Pro 15 OLED',
    cpu_name: 'Intel Core i9-13900H',
    cpu_score: 92,
    gpu_name: 'NVIDIA GeForce RTX 4050 (6GB)',
    gpu_score: 70,
    ram_gb: 16,
    storage_type: 'SSD',
    storage_gb: 1024,
    display_size: 15.6,
    refresh_rate: 120,
    battery_wh: 70.0,
    weight_kg: 1.80,
    price: 99990,
    currency: 'INR',
    os: 'Windows 11',
    category: 'Creative',
    confidence_score: 89.0,
    wilson_lower_bound: 0.869,
    positive_ratio: 92.0,
    review_count: 49,
    clean_review_count: 44
  },
  {
    brand: 'ASUS',
    model_name: 'ROG Strix SCAR 16',
    cpu_name: 'Intel Core i9-14900HX',
    cpu_score: 98,
    gpu_name: 'NVIDIA GeForce RTX 4090 (16GB)',
    gpu_score: 98,
    ram_gb: 32,
    storage_type: 'SSD',
    storage_gb: 2048,
    display_size: 16.0,
    refresh_rate: 240,
    battery_wh: 90.0,
    weight_kg: 2.65,
    price: 279990,
    currency: 'INR',
    os: 'Windows 11',
    category: 'Gaming',
    confidence_score: 96.8,
    wilson_lower_bound: 0.948,
    positive_ratio: 98.5,
    review_count: 54,
    clean_review_count: 49
  },
  {
    brand: 'Acer',
    model_name: 'Swift Go 14 OLED',
    cpu_name: 'Intel Core Ultra 5 125H',
    cpu_score: 74,
    gpu_name: 'Intel Arc Graphics',
    gpu_score: 50,
    ram_gb: 16,
    storage_type: 'SSD',
    storage_gb: 512,
    display_size: 14.0,
    refresh_rate: 90,
    battery_wh: 65.0,
    weight_kg: 1.32,
    price: 69990,
    currency: 'INR',
    os: 'Windows 11',
    category: 'Everyday',
    confidence_score: 86.8,
    wilson_lower_bound: 0.846,
    positive_ratio: 89.8,
    review_count: 45,
    clean_review_count: 40
  },
  {
    brand: 'Acer',
    model_name: 'Predator Helios 16',
    cpu_name: 'Intel Core i7-13700HX',
    cpu_score: 88,
    gpu_name: 'NVIDIA GeForce RTX 4070 (8GB)',
    gpu_score: 88,
    ram_gb: 16,
    storage_type: 'SSD',
    storage_gb: 1024,
    display_size: 16.0,
    refresh_rate: 240,
    battery_wh: 90.0,
    weight_kg: 2.60,
    price: 149990,
    currency: 'INR',
    os: 'Windows 11',
    category: 'Gaming',
    confidence_score: 89.5,
    wilson_lower_bound: 0.874,
    positive_ratio: 92.5,
    review_count: 52,
    clean_review_count: 46
  },
  {
    brand: 'Acer',
    model_name: 'Aspire 5 A515',
    cpu_name: 'AMD Ryzen 5 7520U',
    cpu_score: 55,
    gpu_name: 'AMD Radeon 610M',
    gpu_score: 28,
    ram_gb: 8,
    storage_type: 'SSD',
    storage_gb: 512,
    display_size: 15.6,
    refresh_rate: 60,
    battery_wh: 50.0,
    weight_kg: 1.75,
    price: 41990,
    currency: 'INR',
    os: 'Windows 11',
    category: 'Budget',
    confidence_score: 75.0,
    wilson_lower_bound: 0.728,
    positive_ratio: 80.0,
    review_count: 56,
    clean_review_count: 48
  },
  {
    brand: 'Acer',
    model_name: 'Nitro 16',
    cpu_name: 'AMD Ryzen 7 7735HS',
    cpu_score: 80,
    gpu_name: 'NVIDIA GeForce RTX 4060 (8GB)',
    gpu_score: 78,
    ram_gb: 16,
    storage_type: 'SSD',
    storage_gb: 512,
    display_size: 16.0,
    refresh_rate: 165,
    battery_wh: 90.0,
    weight_kg: 2.70,
    price: 99990,
    currency: 'INR',
    os: 'Windows 11',
    category: 'Gaming',
    confidence_score: 86.2,
    wilson_lower_bound: 0.840,
    positive_ratio: 89.0,
    review_count: 50,
    clean_review_count: 43
  },
  {
    brand: 'MSI',
    model_name: 'Stealth 16 Studio',
    cpu_name: 'Intel Core i9-13900H',
    cpu_score: 92,
    gpu_name: 'NVIDIA GeForce RTX 4070 (8GB)',
    gpu_score: 88,
    ram_gb: 32,
    storage_type: 'SSD',
    storage_gb: 1024,
    display_size: 16.0,
    refresh_rate: 240,
    battery_wh: 99.9,
    weight_kg: 1.99,
    price: 184990,
    currency: 'INR',
    os: 'Windows 11',
    category: 'Creative',
    confidence_score: 91.0,
    wilson_lower_bound: 0.888,
    positive_ratio: 93.5,
    review_count: 44,
    clean_review_count: 39
  },
  {
    brand: 'MSI',
    model_name: 'Raider GE78 HX',
    cpu_name: 'Intel Core i9-14900HX',
    cpu_score: 98,
    gpu_name: 'NVIDIA GeForce RTX 4080 (12GB)',
    gpu_score: 94,
    ram_gb: 32,
    storage_type: 'SSD',
    storage_gb: 2048,
    display_size: 17.0,
    refresh_rate: 240,
    battery_wh: 99.9,
    weight_kg: 3.10,
    price: 289990,
    currency: 'INR',
    os: 'Windows 11',
    category: 'Gaming',
    confidence_score: 94.5,
    wilson_lower_bound: 0.924,
    positive_ratio: 96.5,
    review_count: 48,
    clean_review_count: 43
  },
  {
    brand: 'MSI',
    model_name: 'Modern 14 C12M',
    cpu_name: 'Intel Core i3-1215U',
    cpu_score: 52,
    gpu_name: 'Intel UHD Graphics',
    gpu_score: 25,
    ram_gb: 8,
    storage_type: 'SSD',
    storage_gb: 512,
    display_size: 14.0,
    refresh_rate: 60,
    battery_wh: 39.3,
    weight_kg: 1.40,
    price: 37990,
    currency: 'INR',
    os: 'Windows 11',
    category: 'Budget',
    confidence_score: 78.2,
    wilson_lower_bound: 0.760,
    positive_ratio: 82.5,
    review_count: 42,
    clean_review_count: 36
  },
  {
    brand: 'Razer',
    model_name: 'Blade 14 (2024)',
    cpu_name: 'AMD Ryzen 9 8945HS',
    cpu_score: 94,
    gpu_name: 'NVIDIA GeForce RTX 4070 (8GB)',
    gpu_score: 88,
    ram_gb: 32,
    storage_type: 'SSD',
    storage_gb: 1024,
    display_size: 14.0,
    refresh_rate: 240,
    battery_wh: 68.1,
    weight_kg: 1.84,
    price: 219990,
    currency: 'INR',
    os: 'Windows 11',
    category: 'Gaming',
    confidence_score: 92.4,
    wilson_lower_bound: 0.903,
    positive_ratio: 94.5,
    review_count: 45,
    clean_review_count: 40
  },
  {
    brand: 'Razer',
    model_name: 'Blade 16 (2024) Dual-OLED',
    cpu_name: 'Intel Core i9-14900HX',
    cpu_score: 98,
    gpu_name: 'NVIDIA GeForce RTX 4080 (12GB)',
    gpu_score: 94,
    ram_gb: 32,
    storage_type: 'SSD',
    storage_gb: 1024,
    display_size: 16.0,
    refresh_rate: 240,
    battery_wh: 95.2,
    weight_kg: 2.45,
    price: 299990,
    currency: 'INR',
    os: 'Windows 11',
    category: 'Gaming',
    confidence_score: 94.0,
    wilson_lower_bound: 0.920,
    positive_ratio: 96.0,
    review_count: 46,
    clean_review_count: 41
  },
  {
    brand: 'Microsoft',
    model_name: 'Surface Laptop 5 13.5"',
    cpu_name: 'Intel Core i5-1235U',
    cpu_score: 65,
    gpu_name: 'Intel Iris Xe Graphics',
    gpu_score: 38,
    ram_gb: 8,
    storage_type: 'SSD',
    storage_gb: 512,
    display_size: 13.5,
    refresh_rate: 60,
    battery_wh: 47.4,
    weight_kg: 1.27,
    price: 94990,
    currency: 'INR',
    os: 'Windows 11',
    category: 'Productivity',
    confidence_score: 87.0,
    wilson_lower_bound: 0.849,
    positive_ratio: 90.0,
    review_count: 40,
    clean_review_count: 35
  },
  {
    brand: 'Microsoft',
    model_name: 'Surface Pro 9 (2-in-1)',
    cpu_name: 'Intel Core i7-1255U',
    cpu_score: 76,
    gpu_name: 'Intel Iris Xe Graphics',
    gpu_score: 40,
    ram_gb: 16,
    storage_type: 'SSD',
    storage_gb: 256,
    display_size: 13.0,
    refresh_rate: 120,
    battery_wh: 47.7,
    weight_kg: 0.88,
    price: 99990,
    currency: 'INR',
    os: 'Windows 11',
    category: '2-in-1',
    confidence_score: 88.2,
    wilson_lower_bound: 0.860,
    positive_ratio: 91.5,
    review_count: 43,
    clean_review_count: 38
  },
  {
    brand: 'Samsung',
    model_name: 'Galaxy Book4 Pro 360',
    cpu_name: 'Intel Core Ultra 7 155H',
    cpu_score: 85,
    gpu_name: 'Intel Arc Graphics',
    gpu_score: 55,
    ram_gb: 16,
    storage_type: 'SSD',
    storage_gb: 1024,
    display_size: 16.0,
    refresh_rate: 120,
    battery_wh: 76.0,
    weight_kg: 1.66,
    price: 159990,
    currency: 'INR',
    os: 'Windows 11',
    category: 'Creative',
    confidence_score: 92.5,
    wilson_lower_bound: 0.905,
    positive_ratio: 94.8,
    review_count: 45,
    clean_review_count: 40
  }
];

export async function resetAndSeedCleanDataset(knex: Knex): Promise<void> {
  console.log('[TrueSpec Auto-Seeder] Resetting database tables to clean state...');
  await knex('laptop_scores').del().catch(() => {});
  await knex('reviews').del().catch(() => {});
  await knex('laptops').del().catch(() => {});

  console.log('[TrueSpec Auto-Seeder] Populating 36+ verified INR laptops and confidence scores...');
  await seedDefaultLaptopsIfEmpty(knex);
}

export async function seedDefaultLaptopsIfEmpty(knex: Knex): Promise<void> {
  const laptopCountRes = await knex('laptops').count<{ total: number }>('id as total').first();
  const currentCount = laptopCountRes ? Number(laptopCountRes.total) : 0;

  if (currentCount > 0) {
    // Check if laptop_scores has entries
    const scoreCountRes = await knex('laptop_scores').count<{ total: number }>('id as total').first();
    const scoreCount = scoreCountRes ? Number(scoreCountRes.total) : 0;
    if (scoreCount > 0) {
      return; // Already seeded and scored
    }
  }

  console.log('[TrueSpec Auto-Seeder] Seeding default laptop dataset and precomputed TrueSpec confidence scores into database...');

  for (const item of DEFAULT_LAPTOPS) {
    // Check if laptop exists
    let existing = await knex('laptops').where('brand', item.brand).andWhere('model_name', item.model_name).first();
    let laptopId: number;

    if (!existing) {
      const [insertedId] = await knex('laptops').insert({
        brand: item.brand,
        model_name: item.model_name,
        cpu_name: item.cpu_name,
        cpu_score: item.cpu_score,
        gpu_name: item.gpu_name,
        gpu_score: item.gpu_score,
        ram_gb: item.ram_gb,
        storage_type: item.storage_type,
        storage_gb: item.storage_gb,
        display_size: item.display_size,
        refresh_rate: item.refresh_rate,
        battery_wh: item.battery_wh,
        weight_kg: item.weight_kg,
        price: item.price,
        currency: item.currency,
        os: item.os,
        category: item.category
      });
      laptopId = typeof insertedId === 'number' ? insertedId : (insertedId as any)?.id || 1;
      // In MySQL knex insert returns [insertId]
      if (!laptopId && typeof insertedId === 'object') {
        const fetched = await knex('laptops').where('brand', item.brand).andWhere('model_name', item.model_name).first();
        laptopId = fetched?.id;
      }
    } else {
      laptopId = existing.id;
    }

    if (!laptopId) continue;

    // Seed laptop_scores entry
    const existingScore = await knex('laptop_scores').where('laptop_id', laptopId).first();
    if (!existingScore) {
      await knex('laptop_scores').insert({
        laptop_id: laptopId,
        confidence_score: item.confidence_score,
        wilson_lower_bound: item.wilson_lower_bound,
        positive_ratio: item.positive_ratio,
        review_count: item.review_count,
        clean_review_count: item.clean_review_count
      });
    }

    // Seed sample genuine reviews & flagged sample reviews
    const existingReviews = await knex('reviews').where('laptop_id', laptopId).count<{ total: number }>('id as total').first();
    if (!existingReviews || Number(existingReviews.total) === 0) {
      await knex('reviews').insert([
        {
          laptop_id: laptopId,
          source: 'Verified Customer',
          review_text: `Exceptional machine for daily workloads. The screen clarity is stunning and battery backup comfortably lasts through full work sessions.`,
          rating: 5,
          verified_purchase: true,
          is_flagged: false,
          sentiment_label: 'positive'
        },
        {
          laptop_id: laptopId,
          source: 'Verified Customer',
          review_text: `Build quality is solid and typing on the keyboard feels very responsive. Compiles code and handles multitasking smoothly.`,
          rating: 5,
          verified_purchase: true,
          is_flagged: false,
          sentiment_label: 'positive'
        },
        {
          laptop_id: laptopId,
          source: 'Verified Customer',
          review_text: `Decent daily performer. Gets slightly warm under high load, but overall offers solid value for the price.`,
          rating: 4,
          verified_purchase: true,
          is_flagged: false,
          sentiment_label: 'neutral'
        },
        {
          laptop_id: laptopId,
          source: 'Community Review',
          review_text: `BEST EVER BUY NOW CHEAPEST DEAL CLICK HERE http://spam-deal-link.com/promo AMAZING BUY IT NOW!!!!!!`,
          rating: 5,
          verified_purchase: false,
          is_flagged: true,
          sentiment_label: 'positive'
        }
      ]);
    }
  }

  console.log('[TrueSpec Auto-Seeder] Successfully seeded database with all laptops, reviews, and confidence scores.');
}
